name: flutter_inappwebview_proxy_windows
description: Windows implementation of the inapp_web_view_proxy plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_proxy:
    path: ../flutter_inappwebview_proxy
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: flutter_inappwebview_proxy
    platforms:
      windows:
        package: chat.chums.flutter_inappwebview_proxy
        dartPluginClass: InappWebViewProxyWindows


