name: flutter_inappwebview_proxy
description: Flutter package of the flutter_inappwebview_proxy plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_proxy_android
      ios:
        default_package: flutter_inappwebview_proxy_ios

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^6.1.5
  http: ^1.3.0
  flutter_inappwebview_proxy_android:
    path: ../flutter_inappwebview_proxy_android
  flutter_inappwebview_proxy_ios:
    path: ../flutter_inappwebview_proxy_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


